### PR TITLE
Packaging and testing improvements

### PR DESCRIPTION
**Pull request by agronholm**
This PR adds missing packaging/testing boilerplate. What is still missing is:

1. Encrypted PyPI password for automated PyPI deployment via Travis
1. The "long" description that goes to the PyPI page. I feel that both READMEs (of which there should only be one!) are too long for that purpose.

If you provide this missing information, I will amend my commits so you can merge while maintaining a pretty version history. You can also now enable Travis integration in github's repository settings.

### CODE REVIEW

**Comment by agronholm** [comment]
One more thing: if you want to have command line tools, the entry points need to be declared in setup.py. We talked about that stub generator tool but I don't remember where we left on that subject.

**Comment by Stewori** [comment]
secure:
```
g3MmFBjhaVdDWeJ5OUx02dNU3l37k6Ytxm5fpgCXjK7ybDd8RRZmAjuvjX2ZzjTozMeJG3AsYowd0jvQlNWqP0v0fpnSdCgWo0ucIPyd9mErBvwJPC98KJl6CFrQ6JgOSa7RK5Zibnncgpwrsbgww4Hz7+8m1XDZPOP0BrjxWU1nj4VpRyP2Gf0Jd1ecJYNTLJckzMfFJd4Bizw++8nqmxejF/sXc3bg9YEqIxGBzlGtQSyGUjx22pSReCgQawBjVsd2DaVkl7EmzMYNZqV8JTN5L8Wt5aH3B86BNBjaXQy5MnK3ZcuEUEBMs/8qbXgmrKZAZgtyfQ7wZuNvpbSuheeSO8CTnZTD1PjkTfS9iXlcJlVijdzKqd6ymcV8cAj+VDVB9bd0JJ0hV8vs9gbs29UC+mgnZopv+vByhFOW3xwfg4RBuEIoaXFqdP5JL61n0ZbFnoM53etEjcJfo14iKmGC3WW5KjDrOCnVXAYqoDIaPyqqrjJUERWCglkFfEhRiYH8RCzqv36KRqf/jqOwQgRA3+nuO5/ttSkP1uZktem1Jv9ZH2moZbWV9H5iY6mJMY9jYWPjv+lkflUG1ZTduJUMAJzsUMaSnFsJzZuFn46/unEPmN0ob2s7oX0mgkPpWJAAw1drMzWoGX/CpneqGE1DSW5AhibMkhf/tAZBfJ8=
```

Regarding pypi description: I would use a reduced version of the readme. What do you think it should contain? How should I submit it? Add another file to github? How shall I call it?

Regarding command line tools: You suggested the name `typestubs`. I wanted a name that contains "converter" or "conv", e.g. `typestub_conv` or `python2_stub_conv`. It occurred to me that I could rather easily generalize the converter to produce a stubfile (python 2 style or python 3) from any input python script rather than only from other stubfiles. So it could additionally be used to help moving ordinary in-code type-hints into a stubfile (for whatever usecase one might have). So the name should maybe not be python2-specific, nor converter specific. What about `stubgen` or `typestubgen`?
Actually under this perspective your original suggestion `typestubs` is not bad. I'm undecided.

One note:
My pypi username is `stefan.richthofer`, only my github name is `Stewori`. I hope it doesn't cause trouble.

**Comment by agronholm** [comment]
I've made the changes. You can edit the entry point name to your liking.

**Comment by agronholm** [comment]
As for the readme, I'm currently selectively including my README.rst in the documentation. Would this approach work for you?

**Comment by Stewori** [comment]
What do you mean by "selectively"? E.g. I would put - let's say - pypi.rst into the repo, containing a reduced readme and add `long_description=pypi.rst` to `setup.py`? Or is there a better way?

**Comment by agronholm** [comment]
Let me put it this way: do you agree with how typeguard works in this respect (look at its documentation, README.rst and setup.py)?

**Comment by Stewori** [comment]
Sure, I'd completely agree to do it like in typeguard. But typeguard uses readme.rst as pypi page (or do I overlook something?) and you earlier noted that pytypes readme is too long for a pypi description.

**Comment by agronholm** [comment]
Yes. Given the fact that pytypes has substantially more functionality than typeguard, it would be best to have README.rst serve as the PyPI page content and make a separate Sphinx documentation.

**Comment by Stewori** [comment]
readme.rst contains only a quick manual for the most important features. I find it important that people can see some usage of most important features directly on the frontpage. I will try to shorten it somewhat, especially the longer examples. But you can already setup stuff like in typeguard.

Having a separate proper sphinx documentation is a different front. Let's postpone that.

Like you already suggested, we should move test_typechecker.py and the testhelpers directory out of pytypes package. These shouldn't be distributed via pip, should they? (maybe as separate package?) How to do that (in addition to moving the folder)?

**Comment by agronholm** [comment]
Ok, so I'll use readme.rst for the pypi page, right?

**Comment by agronholm** [comment]
I'll think of something for the tests. Do you want to use setuptools_scm or similar? That would eliminate the need for a MANIFEST.in but has some disadvantages like not being able to install from a github tarball (as it contains no metadata). I am using it in all of my projects and I consider the drawbacks smaller than the advantages.

**Comment by Stewori** [comment]
I'm fine with setuptools_scm. You have more experience with this topic; I'll leave it to your assessment.
One thing: Let's better continue such discussion in a new issue/thread, rather than appended to a closed PR...

**Pull request merged**
