### PR TITLE
Optimize resolve_fw_decl

### PR DESCRIPTION
**Pull request by mitar**
This is a huge time-saver. Otherwise globals for `resolve_fw_decl` are being rebuild again and again our case, which just blows up. It brings 4 minutes loading time (we do some type checking at loading time) to 14 seconds.

See crazy slow trace [here](https://gist.github.com/remram44/455bfd4d95bf6af15fe5c11114cc0369).

So `resolve_fw_decl` calls `get_function_perspective_globals` which then calls `getframeinfo` 53240 times which calls `getmodule` 81927 times and this is just slow. In our case cache has just 8 entries (I left it to default 128) at the end for this speedup:

```
CacheInfo(hits=1414, misses=8, maxsize=128, currsize=8)
```

### CODE REVIEW

**Comment by mitar** [comment]
OK, this does not seem to work correctly and is breaking tests.

**Comment by Stewori** [comment]
I guess the issue is that ``get_function_perspective_globals`` inherently cannot be cached, because its result depends on the caller which is not explicitly part of the call's arguments.
``resolve_fw_decl`` optionally takes a custom globals argument ``globs`` where you can specify what it is supposed to consider global. Maybe you could cache the ``globs`` object. If ``resolve_fw_decl`` is called with ``globs`` != ``None``, it does not call slow ``get_function_perspective_globals``.

In general we can maybe introduce caching of ``resolve_fw_decl`` results. I think the forward references involved in a code base are usually limited...

**Comment by mitar** [comment]
See also my comment [on this thread](https://stackoverflow.com/questions/15608987/access-variables-of-caller-function-in-python).

**Comment by Stewori** [comment]
The thing is (IIRC) we cannot make assumptions about the position from where ``resolve_fw_decl`` is called. It might be unrelated to the position of ``Foo``. Maybe there are name conflicts between the variables visible from the locations or for ``Foo`` something is visible that is not visible for the caller. And remember: ``resolve_fw_decl`` is especially about resolving variables not visible from ``Foo``'s location. ``get_function_perspective_globals`` is intended to obtain the caller's view from within ``resolve_fw_decl`` to obtain a pool of variables for resolving references in ``Foo``.

Now it occurs to me that maybe just calling the builtin function ``globals()`` might have the same effect at lower cost than walking the stack. I'm not sure right now, but will try.
Anyway, you can try the workaround to always call ``resolve_fw_decl`` with ``globs=globals()``.

**Comment by Stewori** [comment]
> You are right. It is not important from where resolve_fw_decl gets called. So not sure why we are walking the stack? :-)

> But this is not what you want. You want a view inside which Foo is defined (with any later variables available). Not where you are calling resolve_fw_decl from. You agree with that above, no?

This was just a heuristic/best effort, to assume the caller sees everything necessary, given that it can also see ``Foo`` and that the caller assumes that ``Foo`` can be resolved now. Taking caller's view was always meant as a fallback if no explicit context was provided. So, you'd prefer to remove this fallback, right? I'll think about it.

**Comment by mitar** [comment]
Yea. It is a very costly fallback.

So maybe you can go just one stack frame up, if you want to know what caller sees. But you traverse whole stack, from level all the way up (or is the other direction)? I would think that you have to just get locals of frame at given outside level.

**Comment by Stewori** [comment]
Okay, I changed the following in https://github.com/Stewori/pytypes/commit/dd26244a27fb76f4cca40348a8e25d07680a00ca:

- search only two levels for __locals__ by default
- by setting search_stack_depth=0, stack searching can easily be prevented
- wrote some doc for resolve_fw_decl, including a warning regarding this issue and advice to provide a proper ``globs``.

**Comment by mitar** [comment]
This looks great! Thanks.

**Comment by mitar** [comment]
Any plans for a release sometime soon?

**Comment by Stewori** [comment]
Originally I wanted to get it working with upcoming Python 3.7. However, 3.7 is still some months away, so this is may be not (yet) a release blocker. And I'm thinking of improving on the ``List`` issue discussed at https://github.com/Stewori/pytypes/issues/21#issuecomment-381291693
Anyway, that is maybe a bigger change and should rather be done right after a release and not right before.
So, I'll be thinking about blocker for another day or so, but I guess I'd be fine with a release (it's never perfect anyway...)

**Pull request closed without merging**
